# Generated by Django 3.0.8 on 2020-10-20 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2020, 10, 20, 10, 11, 44, 744583)),
        ),
    ]
